project:
  type: website
  resources: Assets
  output-dir: docs

website:
  title: "Tiger Teng"
  navbar:
    background: "#7BAFD4"
    foreground: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/tiger-jinghao-teng-33a74b21a/
      - icon: github
        href: https://github.com/TigerTeng1024
      - icon: file-pdf
        href: Assets/Tiger_Teng_Resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



